---
git_fullname: Muhammet Orazov
git_username: morazow
git_email: m.orazow@gmail.com

dot_files:
  - .agignore
  - .bash_profile
  - .bashrc
  - .bashrc.d
  - .curlrc
  - .ctags
  - .emacs.d
  - .gemrc
  - .gitignore
  - .git_template
  - .inputrc
  - .tmux.conf
  - .vimrc
  - .wgetrc

dot_templates:
  - .gitconfig

dot_files_absent:
  - .bash_logout
  - .profile
