---
language: generic

matrix:
  include:
    # Ubuntu Trusty (14.04)
    - os: linux
      dist: trusty
      sudo: required

    # High Sierra (10.13)
    - os: osx
      osx_image: xcode9.3

    # Sierra (10.12)
    - os: osx
      osx_image: xcode9.2

    # El Capitan (10.11)
    - os: osx
      osx_image: xcode8

cache:
  apt: true
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  # Uninstall existing brew installation.
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
      chmod +x ./uninstall
      ./uninstall --force
      sudo rm -rf /usr/local/Homebrew
      sudo rm -rf /usr/local/Caskroom
      sudo rm -rf /usr/local/bin/brew
    fi

script:
  - travis_wait 30 ./run

  # Idempotence Test
  - idempotence=$(mktemp)
  - ansible-playbook -i ./hosts site.yml | tee -a ${idempotence}
  # Check idempotence test in non-osx systems, since I could not manage to get homebrew bundle
  # install to be idempotent yet
  - >
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      tail ${idempotence} | grep -q 'changed=0.*failed=0' \
      && (echo 'Idempotence test: pass' && exit 0) \
      || (echo 'Idempotence test: fail' && exit 1)
    fi
  - cat ${idempotence}

after_script:
  - ls -la ~/

notifications:
  email:
    recipients:
      - m.orazow@gmail.com
    on_success: never
    on_failure: always
