---
language: generic

matrix:
  include:
    # Ubuntu Trusty (14.04)
    - os: linux
      dist: trusty
      sudo: required

    # High Sierra (10.13)
    - os: osx
      osx_image: xcode9.3

    # Sierra (10.12)
    - os: osx
      osx_image: xcode9.2

    # El Capitan (10.11)
    - os: osx
      osx_image: xcode8

cache:
  apt: true
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  # Uninstall existing brew installation.
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
      chmod +x ./uninstall
      ./uninstall --force
      sudo rm -rf /usr/local/Homebrew
      sudo rm -rf /usr/local/Caskroom
      sudo rm -rf /usr/local/bin/brew
    fi

script:
  - travis_wait 30 ./run

  # Idempotence Test
  # https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis
  - >
    ansible-playbook -i ./hosts site.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_script:
  - ls -la ~/

notifications:
  email: false
