---
language: generic

sudo: required

os:
  - linux
  - osx

cache:
  apt: true
  pip: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  # Uninstall existing brew installation.
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl -sLO https://raw.githubusercontent.com/Homebrew/install/master/uninstall
      chmod +x ./uninstall
      ./uninstall --force
      sudo rm -rf /usr/local/Homebrew
      sudo rm -rf /usr/local/Caskroom
      sudo rm -rf /usr/local/bin/brew
    fi

install:
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget --no-check-certificate https://bootstrap.pypa.io/get-pip.py
      export GET_PIP_SHA=b7296a5fb2b505c1f97c14200b610c375b22192bdfbd10eea0a3786e0e04a04f
      echo "$GET_PIP_SHA  get-pip.py" | shasum -a 256 -c
      sudo -H python get-pip.py
      pip install -U pip
      sudo pip install ansible
    fi

script:
  - travis_wait 30 ./run

  # Idempotence Test
  # https://blog.travis-ci.com/2017-11-30-testing-ansible-roles-using-docker-on-travis
  - >
    ansible-playbook -i ./hosts site.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_script:
  - ls -la ~/

notifications:
  email: false
