language: generic

addons:
  apt:
    packages:
      - shellcheck

matrix:
  include:
    # Ubuntu Trusty (14.04)
    - os: linux
      dist: trusty
      sudo: required

    # High Sierra (10.13)
    - os: osx
      osx_image: xcode9.3

    # Sierra (10.12)
    - os: osx
      osx_image: xcode9.2

before_install:
  # Install shellcheck on osx.
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install shellcheck
    fi

install:
  - shellcheck --version

script:
  - ./run
  - ./test

after_script:
  - ls -la ~/

notifications:
  email:
    recipients:
      - m.orazow@gmail.com
    on_success: never
    on_failure: always
