---

- src: https://github.com/elliotweiser/ansible-osx-command-line-tools
  name: elliotweiser.osx-command-line-tools
  version: 2.0.1
  path: vendor/roles

- src: https://github.com/geerlingguy/ansible-role-homebrew
  name: geerlingguy.homebrew
  version: 2.4.1
  path: vendor/roles
