#!/usr/bin/env bash

## set -o errexit
## Exits the current script if any of statements return non-true value.
set -e

## set -o nounset
## Exits the script if an uninitialized variable is used.
set -u

## Trap errors in subshells and functions.
set -o errtrace

## If any of the commands fail with a non-zero exit code, then abort the
## entire pipeline with that exit code.
set -o pipefail

HOST_OS=$(uname)
if test "$HOST_OS" = "Darwin"; then
    echo "Running on MacOS!"
elif test "$HOST_OS" = "Linux"; then
    echo "Running on Linux!"
else
    echo "Unknown host OS: $HOST_OS"
    exit 1
fi

CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$CWD"

remove_not_needed () {
    rm -f ~/.profile
    rm -f ~/.bash_logout
}

create_symlinks () {
    cd "${CWD}"/home/
    for dot in *
    do
        if [ $dot = "vim" ]; then
            continue
        fi
        echo "Linking ${dot} file."
        rm -f "$HOME/.${dot}"
        ln -sf "${CWD}/home/${dot}" "$HOME/.${dot}"
    done
}

setup_vim () {
    mkdir -p ~/.vim/{autoload,backup,bundle,spell,tmp,undo}/
    ln -sf "${CWD}/home/vim/updatePlugins.sh" "$HOME/.vim/updatePlugins.sh"
    ln -sf "${CWD}/home/vim/spell/en.utf-8.add" "$HOME/.vim/spell/en.utf-8.add"

    cd ~/.vim
    wget "https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim" -O "autoload/pathogen.vim"
    ./updatePlugins.sh
}

setup_nvim () {
    echo "Setting up neovim"
    mkdir -p ~/.config/nvim/{autoload,undo,spell}/
    local plug_url="https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    curl -fLo ~/.config/nvim/autoload/plug.vim "$plug_url"
    ln -sf "${CWD}/config/init.vim" "$HOME/.config/nvim/init.vim"
    ln -sf "${CWD}/config/coc.vim" "$HOME/.config/nvim/coc.vim"
    ln -sf "${CWD}/config/coc-settings.json" "$HOME/.config/nvim/coc-settings.json"
    ln -sf "${CWD}/config/en.utf-8.add" "$HOME/.config/nvim/spell/en.utf-8.add"

    echo "Installing Fzf"
    if [ ! -d "$HOME/.fzf" ]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install --bin
    else
        cd ~/.fzf
        git pull origin master
    fi

    echo "Running plug install"
    nvim +PlugInstall +PlugUpdate +PlugClean +qall

    echo "Install nodejs 'curl -sL install-node.now.sh/lts | bash', required for nvim complete (coc)"
}

remove_not_needed
create_symlinks
setup_vim
setup_nvim
