#!/usr/bin/env bash

set -euxo errtrace pipefail

[ -e "${HOME}/.gitconfig" ] && grep "name = morazow" "${HOME}/.gitconfig" && \
[ -e "${HOME}/.bash_profile" ] && \
[ -e "${HOME}/.bashrc.d/exports" ] && \
grep "HISTFILESIZE=-1" "${HOME}/.bashrc.d/exports" && \
[ -e "${HOME}/.bashrc.d/aliases" ] && \
grep "alias path" "${HOME}/.bashrc.d/aliases" && \
[ -e "${HOME}/.bashrc.d/paths" ] && \
echo "${PATH}" | sed -e "s/:/\n/g" | grep "${HOME}/.local/bin"
echo "Success: symlinks of configuration files."
