#!/usr/bin/env bash

set -euxo errtrace pipefail

CWD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$CWD"

run_symcheck () {
    [ -e "${HOME}/.gitconfig" ] && grep "name = morazow" "${HOME}/.gitconfig" && \
    [ -e "${HOME}/.tmux.conf" ] && \
    [ -e "${HOME}/.wgetrc" ] && \
    [ -e "${HOME}/.curlrc" ] && \
    [ -e "${HOME}/.agignore" ] && \
    echo "Success: symlinks of configuration files."
}

run_symcheck
