# Set up environment variables

## XDG Paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
if [ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]; then
    XDG_RUNTIME_DIR=/tmp
fi
export XDG_RUNTIME_DIR

## ZSH
export ZDOTDIR=$XDG_CONFIG_HOME/zsh
export ZSH_CUSTOM=$XDG_CONFIG_HOME/zsh/custom/
