# Zsh Configuration

## Keybindings {{{

bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
# Emacs style
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

## }}}

## History Settings {{{

HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
# }}}

## Zinit Setup {{{

# Directory to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if not already
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

if [ ! -d $ZINIT_HOME/.git ]; then
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source Zinit
source "${ZINIT_HOME}/zinit.zsh"

# Needed only if sourced after compinit
# autoload -Uz _zinit
# (( ${+_comps} )) && _comps[zinit]=_zinit

# }}}

## Zsh Plugins {{{

zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node

zinit wait lucid light-mode for \
    zsh-users/zsh-completions \
    zsh-users/zsh-autosuggestions \
    zdharma-continuum/fast-syntax-highlighting \
    Aloxaf/fzf-tab \
    jonmosco/kube-ps1

# }}}

## Enable Completion System {{{

## Initialize completion system after plugins
autoload -Uz compinit
compinit -d ~/.zcompdump

## Rebuild compdump only once per day
() {
  setopt local_options extended_glob
  autoload -Uz zrecompile
  if [[ -f ~/.zcompdump(#qN.mh+24) ]]; then
    zrecompile -p ~/.zcompdump
    zrecompile -p ~/.zshrc
  fi
}

# }}}

## Prompt Configuration {{{

autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' unstagedstr '%F{red}[±]'
zstyle ':vcs_info:git:*' stagedstr '%F{green}[+]'
zstyle ':vcs_info:*' formats '%F{#7c7c7c}%b%u%c'
zstyle ':vcs_info:*' actionformats '%F{red}%b|%a%u%c'

# Build prompt
PROMPT=''
PROMPT+='%F{blue}%~ ${vcs_info_msg_0_}%f
%F{green}❯%f '

# }}}

## Completion Styling {{{

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
# FZF-Tab configuration (modern completion)
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*:git-checkout:*' sort false
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# }}}

## Shell Integrations {{{

# FZF configuration
eval "$(fzf --zsh)"
# export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'

eval "$(zoxide init zsh)"

# }}}

## Basic Aliases

alias g='git'
alias c='clear'
alias cd='z'
alias nv='nvim'
alias ls='ls --color=auto'
alias ll='ls -lah'

## Basic Exports

export LC_ALL=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

export EDITOR=nvim
export VISUAL=$EDITOR

# XDG Paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
if [ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]; then
    XDG_RUNTIME_DIR=/tmp
fi
export XDG_RUNTIME_DIR

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH="/opt/homebrew/bin:$PATH"
export HOMEBREW_NO_ANALYTICS=1

# Source custom exports file
if [[ -f "$HOME/.exports" ]]; then
    source "$HOME/.exports"
fi

# vim:foldmethod=marker:foldlevel=0
