---

- name: Create a backup directory
  file: path=~/.backups state=directory

- name: Check for non-symlink originals
  command: test -e ~/{{ item }} -a ! -L ~/{{ item }}
  failed_when: original_check.rc > 1
  register: original_check
  with_items: '{{ dot_files + dot_templates }}'
  changed_when: false

- name: Backup originals
  command:
    mv ~/{{ item.0 }} ~/.backups/
    creates=~/.backups/{{ item.0 }}
    removes=~/{{ item.0 }}
  with_together:
    - '{{ dot_files + dot_templates }}'
    - '{{ original_check.results }}'
  when: item.1.rc == 0  # item exists and is not a symlink
  loop_control:
    label: '{{ item.0 }}'
