---

- name: Check if ~/.bash_eternal_history file exists
  stat: path=~/.bash_eternal_history
  register: bash_history_file

- name: Touch ~/.bash_eternal_history file
  file: path=~/.bash_eternal_history state=touch
  when: not bash_history_file.stat.exists

- name: Create symlink of dotfiles (e.g. .vimrc)
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  with_items: '{{ dot_files }}'

- name: Create templated dotfiles (e.g. .gitconfig)
  template: src={{ item }}
            dest=~/{{ item }}
            mode={{ '0755' if item.endswith('.sh') else '0644' }}
            follow=yes
  with_items: '{{ dot_templates }}'
