---
- name: Create symlink files
  file: src={{ ansible_env.PWD }}/roles/dotfiles/files/{{ item }}
        path=~/{{ item }}
        state=link
        force=yes
  with_items: '{{ dot_files }}'

- name: Create templates
  template: src={{ item }}
            dest=~/{{ item }}
            mode={{ '0755' if item.endswith('.sh') else '0644' }}
  with_items: '{{ dot_templates }}'
