---

- name: Make sure that chunkwm tap is installed
  homebrew_tap: name=crisidev/homebrew-chunkwm

- name: Make sure that chunkwm is installed
  homebrew: pkg=chunkwm install_options=with-tmp-logging

- name: Make sure that skhd is installed
  homebrew: pkg=koekeishiya/formulae/skhd install_options=with-logging

- name: Make sure that bitbar is installed
  homebrew_cask: pkg=bitbar

- name: Link chunkwm related dotfiles (e.g. .chunkwmrc)
  file: src={{ ansible_env.PWD }}/roles/tiling/files/{{ item }}
        path=~/{{ item }}
        state=link
        mode=0755
        force=yes
  with_items:
    - .chunkwmrc
    - .skhdrc
    - .bitbar

- name: Check chunkwm service status
  shell: "brew services list | grep 'chunkwm' | tr -s ' ' | cut -d ' ' -f 2"
  register: chunkwm_service
  failed_when: chunkwm_service.stdout == ""
  changed_when: false

- name: chunkwm service is started if not started yet
  command: "brew services start chunkwm"
  when: chunkwm_service.stdout != "started"

- name: Check skhd service status
  shell: "brew services list | grep 'skhd' | tr -s ' ' | cut -d ' ' -f 2"
  register: skhd_service
  failed_when: skhd_service.stdout == ""
  changed_when: false

- name: skhd service is started if not started yet
  command: "brew services start skhd"
  when: skhd_service.stdout != "started"
