---

- name: Get analytics state
  command: brew analytics
  register: brew_analytics
  changed_when: false

- name: Turn off analytics
  command: brew analytics off
  when: '"disabled" not in brew_analytics.stdout'

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Upgrade homebrew
  homebrew: upgrade_all=yes

- name: Tap homebrew bundle
  homebrew_tap: tap=homebrew/bundle state=present

- name: Setup Brewfile to ~/Library/Preferences/Brewfile
  template: src=Brewfile dest="~/Library/Preferences/Brewfile" mode=0644

- name: Check first if dependencies in Brewfile require an update
  command: brew bundle check --file=~/Library/Preferences/Brewfile
  register: bundle_check_result
  ignore_errors: true
  changed_when: false

- name: Run homebrew bundle
  command: brew bundle install --file=~/Library/Preferences/Brewfile
  when: bundle_check_result is failed

- name: Clean up homebrew old versions
  command: brew cleanup
  when: bundle_check_result is failed

- name: Clean up old homebrew casks
  command: brew cask cleanup
  when: bundle_check_result is failed
