---
# Setup homebrew, obtained from https://github.com/geerlingguy/ansible-role-homebrew

- name: Ensure /usr/local has correct permissions (on High Sierra)
  file: path=/usr/local
        owner=root
        state=directory
  become: yes
  when: "ansible_distribution_version.startswith('10.13')"

- name: Ensure /usr/local has correct permissions (on non-'High Sierra' versions of Mac OS X)
  file: path=/usr/local
        owner=root
        group=admin
        state=directory
        mode=0775
  become: yes
  when: "not ansible_distribution_version.startswith('10.13')"

- name: Ensure /usr/local/Homebrew directory exists
  file: path=/usr/local/Homebrew
        owner={{ ansible_user_id }}
        group=admin
        state=directory
        mode=0775
  become: yes

- name: Git clone Homebrew
  git: repo=https://github.com/Homebrew/brew
       dest=/usr/local/Homebrew
       version=master
       update=no
       accept_hostkey=yes
       depth=1

- name: Ensure proper permissions and ownership on /usr/local/bin
  file: path=/usr/local/bin
        state=directory
        owner={{ ansible_user_id }}
        group=admin
        mode=0775
  become: yes

- name: Ensure proper ownership on /usr/local/Homebrew
  file: path=/usr/local/Homebrew
        state=directory
        owner={{ ansible_user_id }}
        group=admin
  become: yes

- name: Check if homebrew binary is already in place
  stat: "path=/usr/local/bin/brew"
  register: homebrew_binary

- name: Symlink brew to /usr/local/bin
  file: src=/usr/local/Homebrew/bin/brew
        dest=/usr/local/bin/brew
        state=link
  when: homebrew_binary.stat.exists == false
  become: yes

- name: Ensure required homebrew folders are in place
  file: path=/usr/local/{{ item }}
        state=directory
        owner={{ ansible_user_id }}
        group=admin
  become: yes
  with_items:
    - Cellar
    - Homebrew
    - Frameworks
    - Caskroom
    - bin
    - etc
    - include
    - lib
    - opt
    - sbin
    - share
    - var

- name: Force update brew after installation
  command: /usr/local/bin/brew update --force
  when: homebrew_binary.stat.exists == false
