---

- name: Create emacs directories
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .emacs.d
    - .emacs.d/backups

- name: Create symlink of emacs files
  file: src={{ ansible_env.PWD }}/roles/emacs/files/{{ item }}
        path={{ ansible_env.HOME }}/.emacs.d/{{ item }}
        state=link
        force=yes
  with_items:
    - lisp
    - custom.el
