---

- name: Create vim directories
  file: path={{ ansible_env.HOME }}/{{ item }} state=directory
  with_items:
    - .vim
    - .vim/tmp
    - .vim/undo
    - .vim/backup
    - .vim/bundle
    - .vim/autoload

- name: Install pathogen
  get_url: url=https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim
           dest={{ ansible_env.HOME }}/.vim/autoload/pathogen.vim

- name: Download vim misc, language and colors plugins
  git: repo={{ item.url }}
       dest={{ ansible_env.HOME }}/.vim/bundle/{{ item.name }}
       version=master
       update=yes
       accept_hostkey=yes
  with_items: '{{ vim_misc + vim_languages + vim_colors }}'
